server:
  port: 8889

pretty:
  # 系统相关配置
  config:
    profile: D:/uploadPath/
  jwt:
    enabled: true # 否开启JWT认证授权功能
    secret: fjkffff;afa # 表示用于JWT签名和解签名的私钥，需要妥善保管。比如使用Jasypt加密。
    expiration: 3600000 # 表示JWT令牌的过期时间，单位是毫秒
    header: accessToken
    useDefaultController: true
    corsAllowedOrigins:
      - http://localhost:3301
    corsAllowedMethods:
      - GET
      - POST
    devOpeningURI:
    permitAllURI:
      - /file/downloadLocal
      - /sysdict//query/page
swagger:
  enable: true # 启用swagger

# mybatis-plus日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pretty-admin?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: abc123
    driver-class-name: com.mysql.cj.jdbc.Driver
  cache:
    type: ehcache
    ehcache:
      config: classpath:/ehcache.xml

logging:
  level:
    root: info
    com.lz.pretty.module.security: debug
  pattern:
    console: '%red(%d{yyyy-MM-dd HH:mm:ss}) %green([%thread]) %highlight(%-5level) %boldMagenta(%logger{10}) - %cyan(%msg%n)'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger : %msg%n'
