server:
  port: 8201

pretty:
  jwt:
    enabled: true # 否开启JWT认证授权功能
    secret: fjkffff;afa # 表示用于JWT签名和解签名的私钥，需要妥善保管。比如使用Jasypt加密。
    expiration: 3600000 # 表示JWT令牌的过期时间，单位是毫秒
    header: JWTHeaderName
    useDefaultController: true
    corsAllowedOrigins:
      - http://localhost:8888
      - http://localhost:8889
    corsAllowedMethods:
      - GET
      - POST

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:13306/pretty-admin?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: abc123
    driver-class-name: com.mysql.cj.jdbc.Driver