server:
  port: 8889

pretty:
  jwt:
    enabled: true # 否开启JWT认证授权功能
    secret: fjkffff;afa # 表示用于JWT签名和解签名的私钥，需要妥善保管。比如使用Jasypt加密。
    expiration: 3600000 # 表示JWT令牌的过期时间，单位是毫秒
    header: JWTHeaderName
    useDefaultController: true
    corsAllowedOrigins:
      - http://localhost:8888
      - http://localhost:8889
    corsAllowedMethods:
      - GET
      - POST
    devOpeningURI:
      - /sysuser/query
      - /sysuser/add
      - /sysuser/update
      - /sysuser/delete
      - /sysuser/pwdreset
      - /sysuser/pwd/isdefulat
      - /sysorg/tree
      - /sysorg/add
      - /sysorg/update
      - /sysorg/delete
      - /sysmenu/tree
      - /sysmenu/add
      - /sysmenu/update
      - /sysmenu/delete
      - /sysmenu/tree/user
      - /sysrole/query
      - /sysrole/add
      - /sysrole/update
      - /sysrole/delete
      - /sysconfig/all
swagger:
  enable: true # 启用swagger

# mybatis-plus日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pretty-admin?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: abc123
    driver-class-name: com.mysql.cj.jdbc.Driver
